// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzRKjOsV8ERmnaqzxsHniEM14lbHk2IqE',
    appId: '1:84510371238:web:f4b8f7a6718aadda02b367',
    messagingSenderId: '84510371238',
    projectId: 'energy-meter-hsss',
    authDomain: 'energy-meter-hsss.firebaseapp.com',
    databaseURL: 'https://energy-meter-hsss-default-rtdb.firebaseio.com',
    storageBucket: 'energy-meter-hsss.appspot.com',
    measurementId: 'G-J2WFJP5NPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeNADcG2PjVDkS0kaTEYBNcdpEmVfD_yQ',
    appId: '1:84510371238:android:3c0901ee0209bddc02b367',
    messagingSenderId: '84510371238',
    projectId: 'energy-meter-hsss',
    databaseURL: 'https://energy-meter-hsss-default-rtdb.firebaseio.com',
    storageBucket: 'energy-meter-hsss.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL4Z-K_dXcBXKsfX9oPT_-mAJjZ7-H5ic',
    appId: '1:84510371238:ios:9dcc49c07c8f4dc802b367',
    messagingSenderId: '84510371238',
    projectId: 'energy-meter-hsss',
    databaseURL: 'https://energy-meter-hsss-default-rtdb.firebaseio.com',
    storageBucket: 'energy-meter-hsss.appspot.com',
    iosClientId: '84510371238-ah7qogi09q0conjiovob8rtgmtt1lt88.apps.googleusercontent.com',
    iosBundleId: 'com.example.energyMeter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL4Z-K_dXcBXKsfX9oPT_-mAJjZ7-H5ic',
    appId: '1:84510371238:ios:9dcc49c07c8f4dc802b367',
    messagingSenderId: '84510371238',
    projectId: 'energy-meter-hsss',
    databaseURL: 'https://energy-meter-hsss-default-rtdb.firebaseio.com',
    storageBucket: 'energy-meter-hsss.appspot.com',
    iosClientId: '84510371238-ah7qogi09q0conjiovob8rtgmtt1lt88.apps.googleusercontent.com',
    iosBundleId: 'com.example.energyMeter',
  );
}
